
require 'momomoto/datatype/base'
require 'momomoto/datatype/boolean'
require 'momomoto/datatype/integer'
require 'momomoto/datatype/smallint'
require 'momomoto/datatype/bigint'
require 'momomoto/datatype/text'
require 'momomoto/datatype/character'
require 'momomoto/datatype/character_varying'
require 'momomoto/datatype/numeric'
require 'momomoto/datatype/real'
require 'momomoto/datatype/bytea'
require 'momomoto/datatype/date'
require 'momomoto/datatype/time_without_time_zone'
require 'momomoto/datatype/interval'
require 'momomoto/datatype/time_with_time_zone'
require 'momomoto/datatype/timestamp_without_time_zone'
require 'momomoto/datatype/timestamp_with_time_zone'
require 'momomoto/datatype/inet'

